#!/usr/bin/env bash
# query_fuzz.sh — Differential query generator for csvql vs DuckDB (#141).
#
# Deliberately scoped down from a full SQL grammar fuzzer (see issue #141 for
# why): single table, WHERE predicates + aggregates only, no JOINs, no
# shrinking. Template-based generation against the known large_test.csv
# schema, run both engines, diff — reuses the same comparison rules as
# verify_correctness.sh's check_approx (numeric rounding tolerance, empty
# field == NULL).
#
# Deterministic: generation uses its own seeded PRNG (mysrand/myrand,
# defined below — NOT awk's built-in srand()/rand(), see the comment at
# their call site for why), so the same --seed always generates the same
# query sequence — a mismatch always reproduces with the exact command
# printed alongside it. On a mismatch, the query pair is dumped to
# tests/regressions/ permanently instead of using a shrinker.
#
# That determinism has two other preconditions, both worth stating since
# they're silent failure modes rather than errors: (1) the CSV fixture must
# be the same bytes every time — generate it with bench/gen_fixture.sh, not
# a one-off ad hoc file; (2) csvql and DuckDB must be the same versions the
# original run used — a replayed seed against different engine versions is
# a legitimate regression check, not a reproduction of the original result.
# See CORRECTNESS.md's "Determinism guarantees" section.
#
# Usage:
#   ./bench/query_fuzz.sh --seed 42 --count 2000
#   ./bench/query_fuzz.sh --seed 42 --count 2000 --csv large_test.csv
#   ./bench/query_fuzz.sh --seed 42 --count 2000 --dump-queries out.sql   # write generated SQL, run nothing
#   ./bench/query_fuzz.sh --seed 42 --count 2000 --check-determinism     # verify same seed -> same stream, run nothing
#
# Environment overrides:
#   DUCKDB_BIN — path to duckdb binary (default: duckdb in PATH)

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CSVQL="${SCRIPT_DIR}/zig-out/bin/csvql"
DUCKDB="${DUCKDB_BIN:-duckdb}"
CSV="${SCRIPT_DIR}/large_test.csv"
SEED=1
COUNT=1000
STOP_ON_FAIL=0
DUMP_QUERIES=""
CHECK_DETERMINISM=0
REGRESSIONS_DIR="${SCRIPT_DIR}/tests/regressions"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --seed) SEED="$2"; shift 2 ;;
    --count) COUNT="$2"; shift 2 ;;
    --csv) CSV="$2"; shift 2 ;;
    --csvql-bin) CSVQL="$2"; shift 2 ;;
    --duckdb-bin) DUCKDB="$2"; shift 2 ;;
    --stop-on-fail) STOP_ON_FAIL=1; shift ;;
    --dump-queries) DUMP_QUERIES="$2"; shift 2 ;;
    --check-determinism) CHECK_DETERMINISM=1; shift ;;
    *) echo "unknown argument: $1" >&2; exit 1 ;;
  esac
done

if [[ ! -f "$CSV" ]]; then
  echo "CSV fixture not found: $CSV"
  exit 1
fi

# --check-determinism: generate the same seed/count twice via --dump-queries
# and diff the results — a direct, continuously-run check of the "same
# seed -> same query stream" guarantee this whole script's reproducibility
# story rests on, rather than just asserting it in prose. This isn't
# theoretical: some awk builds (e.g. mawk compiled against arc4random for
# rand-funcs, rather than a classic seedable PRNG) silently ignore
# srand()'s argument entirely, so the same --seed produces a DIFFERENT
# stream on every invocation. `awk -W version` reports which rand-funcs
# backend is in use. Needs neither csvql nor DuckDB.
if [[ $CHECK_DETERMINISM -eq 1 ]]; then
  DT="$(mktemp -d)"
  trap 'rm -rf "$DT"' EXIT
  "$0" --seed "$SEED" --count "$COUNT" --csv "$CSV" --dump-queries "$DT/run_a.sql"
  "$0" --seed "$SEED" --count "$COUNT" --csv "$CSV" --dump-queries "$DT/run_b.sql"
  # Skip the first line: it's a "Generated by: ... --dump-queries <path>"
  # header that legitimately differs since $DT/run_a.sql != $DT/run_b.sql —
  # not part of the generated query stream itself.
  if diff -q <(tail -n +2 "$DT/run_a.sql") <(tail -n +2 "$DT/run_b.sql") >/dev/null; then
    echo "PASS: seed=$SEED count=$COUNT reproduces identically across two runs"
    exit 0
  else
    echo "FAIL: seed=$SEED count=$COUNT produced DIFFERENT query streams across two runs"
    echo "  awk in use: $(awk -W version 2>&1 | head -1) ($(command -v awk))"
    echo "  this breaks every reproducibility claim in CORRECTNESS.md and VERIFICATION-LOG.md"
    echo "  that depends on --seed alone"
    diff <(tail -n +2 "$DT/run_a.sql") <(tail -n +2 "$DT/run_b.sql") | head -20
    exit 1
  fi
fi

# --dump-queries only needs the CSV fixture (the generator samples real
# string values from it) — it doesn't run either engine, so csvql/duckdb
# don't need to be built/installed just to regenerate the sample file.
if [[ -z "$DUMP_QUERIES" ]]; then
  if [[ ! -x "$CSVQL" ]]; then
    echo "csvql not found at $CSVQL — run: zig build -Doptimize=ReleaseFast"
    exit 1
  fi
  if ! command -v "$DUCKDB" >/dev/null 2>&1; then
    echo "duckdb not found in PATH (set DUCKDB_BIN=/path/to/duckdb)"
    exit 1
  fi
fi

RED='\033[0;31m'
GREEN='\033[0;32m'
DIM='\033[2m'
RESET='\033[0m'

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
QUERIES_FILE="$TMP/queries.tsv"

# ── Generate the query sequence in one awk process (deterministic, given
# --seed) ─────────────────────────────────────────────────────────────────
# Each output line is: kind \t csvql_sql \t duck_sql
# \t is safe as a field separator here since none of the generated SQL
# contains a literal tab.
#
# Uses its own seeded PRNG (mysrand/myrand below) instead of awk's built-in
# srand()/rand(). Deliberately NOT the platform RNG: at least one mawk build
# (compiled against arc4random for its rand-funcs backend, per `awk -W
# version`) silently ignores srand()'s argument and reseeds from OS entropy
# on every process start — so the same --seed produces a different stream
# on every run, which broke this script's core reproducibility guarantee.
# A basic MINSTD LCG, seeded and stepped entirely by our own code, cannot
# depend on which RNG backend the host awk build happens to use.
# See --check-determinism.
awk -v seed="$SEED" -v count="$COUNT" -v csv="$CSV" '
function mysrand(s,    m) {
    m = 2147483647
    rng_state = s % m
    if (rng_state < 0) rng_state += m
    if (rng_state == 0) rng_state = 1
}
function myrand(    m) {
    m = 2147483647
    rng_state = (rng_state * 48271) % m
    return rng_state / m
}
BEGIN {
    mysrand(seed)
    split("id age salary", numeric_cols, " ")
    split("name city department", string_cols, " ")
    split("id name age city salary department", all_cols_any, " ")
    split("COUNT SUM AVG MIN MAX VARIANCE STDDEV MEDIAN", aggs, " ")
    split("= != > >= < <=", numeric_ops, " ")
    split("= !=", string_ops, " ")

    # Sample real values per string column from the fixture (first 5000
    # rows) so string predicates have a realistic hit rate.
    FS = ","
    getline header < csv
    n_hdr = split(header, hdr, ",")
    for (i = 1; i <= n_hdr; i++) col_idx[hdr[i]] = i
    row_n = 0
    while ((getline line < csv) > 0 && row_n < 5000) {
        row_n++
        n_fields = split(line, fields, ",")
        for (j = 1; j <= 3; j++) {
            c = string_cols[j]
            idx = col_idx[c]
            if (idx > 0 && idx <= n_fields && fields[idx] != "") {
                v = fields[idx]
                if (!(c SUBSEP v in seen_values)) {
                    seen_values[c SUBSEP v] = 1
                    n_values[c]++
                    values[c, n_values[c]] = v
                }
            }
        }
    }
    close(csv)

    for (q = 0; q < count; q++) {
        kind_roll = myrand()
        if (kind_roll < 0.26) {
            emit_scalar_agg()
        } else if (kind_roll < 0.52) {
            emit_groupby_agg()
        } else if (kind_roll < 0.74) {
            emit_projection()
        } else if (kind_roll < 0.87) {
            emit_limit_offset()
        } else {
            emit_in_subquery()
        }
    }
}

function pick(arr, n) {
    return arr[int(myrand() * n) + 1]
}

function rand_numeric_val(col) {
    if (col == "id") return int(myrand() * 20000) + 1
    else if (col == "age") return int(myrand() * 50) + 15
    else return int(myrand() * 100000) + 30000
}

function rand_string_val(col,    nv) {
    nv = n_values[col]
    if (nv == 0) return "nobody"
    return values[col, int(myrand() * nv) + 1]
}

function sql_quote(val) {
    gsub(/'"'"'/, "'"'"''"'"'", val)  # escape single quotes for SQL
    return "'"'"'" val "'"'"'"
}

# One "col OP val" predicate — operator set depends on column type.
function gen_predicate() {
    r = myrand()
    if (r < 0.12) {
        # IS NULL / IS NOT NULL — this fixture never has an empty field, so
        # IS NULL always matches zero rows and IS NOT NULL always matches
        # all of them, but that still exercises the operator itself: both
        # engines have to agree on "zero rows" or "every row", not just on
        # a value comparison.
        col = pick(all_cols_any, 6)
        return col ((myrand() < 0.5) ? " IS NULL" : " IS NOT NULL")
    } else if (r < 0.38) {
        col = pick(numeric_cols, 3)
        op = pick(numeric_ops, 6)
        return col " " op " " rand_numeric_val(col)
    } else if (r < 0.48) {
        # BETWEEN low AND high (inclusive numeric range).
        col = pick(numeric_cols, 3)
        v1 = rand_numeric_val(col); v2 = rand_numeric_val(col)
        lo = (v1 < v2) ? v1 : v2; hi = (v1 < v2) ? v2 : v1
        return col " BETWEEN " lo " AND " hi
    } else if (r < 0.62) {
        # LIKE / ILIKE against a substring of a real sampled value —
        # prefix, suffix, or contains wildcard, so it actually matches
        # something instead of testing only the zero-row case.
        col = pick(string_cols, 3)
        val = rand_string_val(col)
        vlen = length(val)
        piece_len = (vlen > 1) ? int(myrand() * (vlen - 1)) + 1 : vlen
        shape = myrand()
        if (shape < 0.34) pattern = substr(val, 1, piece_len) "%"
        else if (shape < 0.67) pattern = "%" substr(val, vlen - piece_len + 1)
        else pattern = "%" substr(val, 1, piece_len) "%"
        kw = (myrand() < 0.5) ? "LIKE" : "ILIKE"
        return col " " kw " " sql_quote(pattern)
    } else if (r < 0.75) {
        col = pick(string_cols, 3)
        op = pick(string_ops, 2)
        return col " " op " " sql_quote(rand_string_val(col))
    } else if (r < 0.87) {
        # IN / NOT IN over a literal list — numeric or string column.
        if (myrand() < 0.5) {
            col = pick(numeric_cols, 3)
            n = int(myrand() * 3) + 2
            list = ""
            for (k = 0; k < n; k++) list = (list == "") ? rand_numeric_val(col) : list ", " rand_numeric_val(col)
        } else {
            col = pick(string_cols, 3)
            n = int(myrand() * 3) + 2
            list = ""
            for (k = 0; k < n; k++) list = (list == "") ? sql_quote(rand_string_val(col)) : list ", " sql_quote(rand_string_val(col))
        }
        kw = (myrand() < 0.5) ? "IN" : "NOT IN"
        return col " " kw " (" list ")"
    } else {
        col = pick(string_cols, 3)
        op = pick(string_ops, 2)
        return col " " op " " sql_quote(rand_string_val(col))
    }
}

# A single predicate, or two joined with AND/OR, optionally wrapped in NOT.
function gen_where() {
    w = gen_predicate()
    if (myrand() < 0.4) {
        joiner = (myrand() < 0.5) ? "AND" : "OR"
        w = w " " joiner " " gen_predicate()
    }
    if (myrand() < 0.1) w = "NOT (" w ")"
    return w
}

function emit_scalar_agg() {
    agg = pick(aggs, 8)
    numcol = pick(numeric_cols, 3)
    where = gen_where()
    arg = (agg == "COUNT" && myrand() < 0.3) ? "*" : numcol
    csvql_sql = "SELECT " agg "(" arg ") FROM '"'"'" csv "'"'"' WHERE " where
    duck_sql = "SELECT " agg "(" arg ") FROM __fuzz_csv WHERE " where
    print "scalar_agg\t" csvql_sql "\t" duck_sql
}

function emit_groupby_agg() {
    group_col = pick(string_cols, 3)
    # Occasionally group by a second, distinct string column too.
    group_col2 = ""
    if (myrand() < 0.3) {
        do { group_col2 = pick(string_cols, 3) } while (group_col2 == group_col)
    }
    group_cols = (group_col2 == "") ? group_col : group_col ", " group_col2

    agg = pick(aggs, 8)
    numcol = pick(numeric_cols, 3)
    where = gen_where()
    arg = (agg == "COUNT" && myrand() < 0.3) ? "*" : numcol

    # Occasionally filter groups post-aggregation with HAVING, using a
    # second (possibly different) aggregate — exercises the aggregate
    # re-evaluation path independent of the SELECT list.
    having = ""
    if (myrand() < 0.3) {
        having_agg = pick(aggs, 8)
        having_col = pick(numeric_cols, 3)
        having_arg = (having_agg == "COUNT" && myrand() < 0.3) ? "*" : having_col
        having_op = pick(numeric_ops, 6)
        having_val = rand_numeric_val(having_col)
        having = " HAVING " having_agg "(" having_arg ") " having_op " " having_val
    }

    csvql_sql = "SELECT " group_cols ", " agg "(" arg ") FROM '"'"'" csv "'"'"' WHERE " where " GROUP BY " group_cols having " ORDER BY " group_cols
    duck_sql = "SELECT " group_cols ", " agg "(" arg ") FROM __fuzz_csv WHERE " where " GROUP BY " group_cols having " ORDER BY " group_cols
    print "groupby_agg\t" csvql_sql "\t" duck_sql
}

# LIMIT n [OFFSET m] over a deterministic ORDER BY id — exercises pagination.
function emit_limit_offset() {
    all_cols_n = 6
    split("id name age city salary department", all_cols, " ")
    n = int(myrand() * 3) + 1
    delete chosen
    cols_str = ""
    got = 0
    while (got < n) {
        c = all_cols[int(myrand() * all_cols_n) + 1]
        if (!(c in chosen)) {
            chosen[c] = 1
            cols_str = (cols_str == "") ? c : cols_str ", " c
            got++
        }
    }
    where = gen_where()
    lim = int(myrand() * 200) + 1
    off = int(myrand() * 500)
    tail = (myrand() < 0.5) ? ("LIMIT " lim " OFFSET " off) : ("OFFSET " off " LIMIT " lim)
    csvql_sql = "SELECT " cols_str " FROM '"'"'" csv "'"'"' WHERE " where " ORDER BY id " tail
    duck_sql = "SELECT " cols_str " FROM __fuzz_csv WHERE " where " ORDER BY id " tail
    print "limit_offset\t" csvql_sql "\t" duck_sql
}

# WHERE col IN/NOT IN (SELECT col FROM <same fixture> WHERE ...) — a
# non-correlated semi-join subquery (#124) against the same table, since
# the generator only knows one fixture schema.
function emit_in_subquery() {
    # outer_col must not be named "col" — gen_where()/gen_predicate() below
    # write the GLOBAL awk variable "col" as a side effect, which would
    # silently clobber it before its second use here (a fuzz-generator bug, not a csvql bug — no GitHub issue).
    outer_col = pick(numeric_cols, 3)
    sub_where = gen_where()
    kw = (myrand() < 0.7) ? "IN" : "NOT IN"
    where = outer_col " " kw " (SELECT " outer_col " FROM '"'"'" csv "'"'"' WHERE " sub_where ")"
    duck_where = outer_col " " kw " (SELECT " outer_col " FROM __fuzz_csv WHERE " sub_where ")"
    # LIMIT caps the outer result: a loose inner predicate (e.g. IS NOT
    # NULL) can resolve to nearly the whole fixture, and an unbounded outer
    # match then makes the awk diff pass compare thousands of rows per
    # query — with enough such queries in one run that dominates wall time
    # without adding real coverage beyond what a capped comparison already
    # exercises.
    csvql_sql = "SELECT id, " outer_col " FROM '"'"'" csv "'"'"' WHERE " where " ORDER BY id LIMIT 200"
    duck_sql = "SELECT id, " outer_col " FROM __fuzz_csv WHERE " duck_where " ORDER BY id LIMIT 200"
    print "in_subquery\t" csvql_sql "\t" duck_sql
}

function emit_projection() {
    all_cols_n = 6
    split("id name age city salary department", all_cols, " ")
    n = int(myrand() * 3) + 1
    # sample n distinct columns without replacement
    delete chosen
    cols_str = ""
    got = 0
    while (got < n) {
        c = all_cols[int(myrand() * all_cols_n) + 1]
        if (!(c in chosen)) {
            chosen[c] = 1
            cols_str = (cols_str == "") ? c : cols_str ", " c
            got++
        }
    }
    where = gen_where()
    # ORDER BY id makes row order deterministic (id is unique) so output
    # can be diffed exactly instead of needing a sort-before-compare step.
    csvql_sql = "SELECT " cols_str " FROM '"'"'" csv "'"'"' WHERE " where " ORDER BY id"
    duck_sql = "SELECT " cols_str " FROM __fuzz_csv WHERE " where " ORDER BY id"
    print "projection\t" csvql_sql "\t" duck_sql
}
' > "$QUERIES_FILE"

# --dump-queries: write the generated csvql-side SQL, one statement per
# line, and stop — no engines involved. This is what regenerates
# bench/sample-queries.sql, the committed sample that lets anyone see the
# actual query shapes this generator produces without reading the awk.
if [[ -n "$DUMP_QUERIES" ]]; then
  {
    echo "-- Generated by: ./bench/query_fuzz.sh --seed $SEED --count $COUNT --dump-queries $DUMP_QUERIES"
    echo "-- Regenerate after any change to the generator's template logic below."
    awk -F'\t' '{print $2 ";"}' "$QUERIES_FILE"
  } > "$DUMP_QUERIES"
  echo "Wrote $COUNT queries to $DUMP_QUERIES"
  exit 0
fi

# ── Batch the DuckDB side into ONE process ──────────────────────────────
# csvql's own startup is ~5ms; the DuckDB CLI's is ~85ms (measured) — nearly
# all of this script's wall time was DuckDB process spawn, not query
# execution. Running N statements through one `duckdb -f` invocation
# instead of N separate invocations is the difference between a few hundred
# queries and tens of thousands in the same wall time.
#
# `.bail off` makes DuckDB continue past a statement error instead of
# aborting the whole batch (default CLI behavior stops at the first error,
# confirmed by testing — a batch with 300+ generated queries WILL contain
# at least one DuckDB-side quirk eventually). A BEGIN/END marker row wraps
# each query so its output block is unambiguous regardless of row count —
# including zero, which is a legitimate result for some generated queries,
# not just a marker of failure.
#
# CREATE TABLE once instead of read_csv_auto() per statement: the CSV
# sniffing/type-inference read_csv_auto does on every call turned out to be
# the dominant cost once process-spawn was eliminated (measured: 300 calls
# to read_csv_auto() in one duckdb process still took ~17s; against a
# pre-materialized table, the same 300 queries took ~0.15s). Every
# generated duck_sql references the fixed table name __fuzz_csv.
BATCH_SQL="$TMP/batch.sql"
BATCH_OUT="$TMP/batch_out.txt"
BATCH_ERR="$TMP/batch_err.txt"
{
  echo ".bail off"
  echo "CREATE TABLE __fuzz_csv AS SELECT * FROM read_csv_auto('${CSV}');"
  i=0
  while IFS=$'\t' read -r _kind _csvql_sql duck_sql; do
    echo "SELECT '@@BEGIN${i}@@' AS m;"
    echo "$duck_sql;"
    echo "SELECT '@@END${i}@@' AS m;"
    i=$((i + 1))
  done < "$QUERIES_FILE"
} > "$BATCH_SQL"

"$DUCKDB" -csv -noheader -f "$BATCH_SQL" > "$BATCH_OUT" 2> "$BATCH_ERR"

# Split the one combined DuckDB output back into per-query files, keyed by
# the BEGIN<i>/END<i> markers.
awk -v tmp="$TMP" '
  /^@@BEGIN[0-9]+@@$/ { idx = substr($0, 8, length($0) - 9); out = tmp "/duck_" idx ".txt"; next }
  /^@@END[0-9]+@@$/ { close(out); out = ""; next }
  out != "" { print > out }
' "$BATCH_OUT"

# ── Run csvql (the irreducible per-query cost — this is the thing under
# test) once per query, raw output only, no pipe through tail/awk/diff. All
# normalization and comparison happens afterward in ONE awk pass instead of
# ~4 subprocess spawns per query (tail + 2×normalize + diff) — that
# bash-loop overhead, not query execution, was the dominant cost once the
# DuckDB side was batched (measured: ~50ms/query wall time against ~5ms
# actual csvql runtime).
total=0
mkdir -p "$REGRESSIONS_DIR"
: > "$TMP/csvql_failures.tsv"
i=0
while IFS=$'\t' read -r kind csvql_sql duck_sql; do
  i=$((i + 1))
  total=$((total + 1))
  "$CSVQL" "$csvql_sql" > "$TMP/csvql_${i}.txt" 2> "$TMP/csvql_err_${i}.txt"
  csvql_rc=$?
  if [[ $csvql_rc -ne 0 ]]; then
    printf '%s\t%s\t%s\t%s\t%s\n' "$i" "$kind" "$csvql_sql" "$duck_sql" "$csvql_rc" >> "$TMP/csvql_failures.tsv"
    if [[ $STOP_ON_FAIL -eq 1 ]]; then break; fi
  fi
done < "$QUERIES_FILE"

declare -a failure_paths=()
failed=0

# Report csvql-side crashes/errors first (these are always real bugs, never
# a "DuckDB disagreed" case).
if [[ -s "$TMP/csvql_failures.tsv" ]]; then
  while IFS=$'\t' read -r i kind csvql_sql duck_sql csvql_rc; do
    echo "[seed=$SEED q=$i] csvql exited $csvql_rc: $csvql_sql"
    sed 's/^/  /' "$TMP/csvql_err_${i}.txt"
    dump_path="$REGRESSIONS_DIR/seed${SEED}_q${i}_${kind}.txt"
    {
      echo "# Reproduce: ./bench/query_fuzz.sh --seed $SEED --count $COUNT --stop-on-fail"
      echo "kind: $kind"
      echo "csvql_sql: $csvql_sql"
      echo "duck_sql: $duck_sql"
      echo "csvql_rc: $csvql_rc"
      echo "--- csvql stderr ---"
      cat "$TMP/csvql_err_${i}.txt"
    } > "$dump_path"
    failure_paths+=("$dump_path")
    failed=$((failed + 1))
  done < "$TMP/csvql_failures.tsv"
fi

# One awk pass: normalize + diff every (csvql_i, duck_(i-1)) file pair and
# report mismatches — replaces what used to be a diff + 2×normalize
# subprocess spawn per query.
MISMATCH_REPORT="$TMP/mismatches.tsv"
awk -v tmp="$TMP" -v total="$total" -v queries_file="$QUERIES_FILE" -v failtsv="$TMP/csvql_failures.tsv" '
  # macOS one-true-awk quirk: a name used as an array anywhere in the
  # program (even in an unrelated function-local scope) cannot also be used
  # as a scalar anywhere else, including a different functions parameter of
  # the same name. Every identifier below is unique across the whole
  # script on purpose — do not reuse a short name like "f" or "line" again.
  function normalize_field(val,    n, mag, dec) {
    if (val == "" || val == "NULL") return "NULL"
    if (val ~ /^-?[0-9]+(\.[0-9]+)?$/) {
      n = val + 0
      mag = (n < 0) ? -n : n
      # Large-magnitude floats (VARIANCE/STDDEV over a big column sum
      # squares into the hundreds of millions) accumulate float64
      # summation-order noise well before the 4th decimal place once the
      # integer part alone has 7+ digits. Rounding tighter than the
      # precision floor of the value itself produces false-positive
      # mismatches, not real bugs -- same reasoning as
      # verify_correctness.sh check_approx `decimals` parameter.
      dec = (mag >= 1000000) ? 0 : 4
      return sprintf("%.*f", dec, n)
    }
    return val
  }
  function normalize_row(rawrow,    nfields, colidx, colparts, outrow, normed) {
    nfields = split(rawrow, colparts, ",")
    if (nfields == 0) return "NULL"
    outrow = ""
    for (colidx = 1; colidx <= nfields; colidx++) {
      normed = normalize_field(colparts[colidx])
      outrow = (colidx == 1) ? normed : outrow "," normed
    }
    return outrow
  }
  function read_rows(path, dest, skip_first,    rowtext, is_header, rowcount) {
    rowcount = 0
    is_header = skip_first
    while ((getline rowtext < path) > 0) {
      if (is_header) { is_header = 0; continue }
      dest[rowcount++] = normalize_row(rowtext)
    }
    close(path)
    return rowcount
  }
  BEGIN {
    while ((getline tsvline < failtsv) > 0) {
      split(tsvline, failparts, "\t")
      skip_idx[failparts[1]] = 1
    }
    close(failtsv)

    qnum = 0
    while ((getline tsvline < queries_file) > 0) {
      qnum++
      if (qnum in skip_idx) continue
      split(tsvline, qparts, "\t")
      qkind = qparts[1]; qcsvql_sql = qparts[2]; qduck_sql = qparts[3]

      n_csvql_rows = read_rows(tmp "/csvql_" qnum ".txt", csvql_rows, 1)  # csvql always writes a header row
      n_duck_rows = read_rows(tmp "/duck_" (qnum - 1) ".txt", duck_rows, 0)  # -noheader: no header row to skip

      row_mismatch = (n_csvql_rows != n_duck_rows)
      if (!row_mismatch) {
        for (rowidx = 0; rowidx < n_csvql_rows; rowidx++) {
          if (csvql_rows[rowidx] != duck_rows[rowidx]) { row_mismatch = 1; break }
        }
      }
      if (row_mismatch) {
        dumpfile = tmp "/dump_" qnum ".txt"
        print "kind: " qkind > dumpfile
        print "csvql_sql: " qcsvql_sql >> dumpfile
        print "duck_sql: " qduck_sql >> dumpfile
        print "--- csvql output (normalized) ---" >> dumpfile
        for (rowidx = 0; rowidx < n_csvql_rows; rowidx++) print csvql_rows[rowidx] >> dumpfile
        print "--- duckdb output (normalized) ---" >> dumpfile
        for (rowidx = 0; rowidx < n_duck_rows; rowidx++) print duck_rows[rowidx] >> dumpfile
        close(dumpfile)
        print qnum "\t" qkind "\t" qcsvql_sql "\t" qduck_sql
      }
    }
  }
' > "$MISMATCH_REPORT"

if [[ -s "$MISMATCH_REPORT" ]]; then
  while IFS=$'\t' read -r i kind csvql_sql duck_sql; do
    echo "[seed=$SEED q=$i] MISMATCH ($kind):"
    echo "  csvql: $csvql_sql"
    echo "  duck:  $duck_sql"
    head -20 "$TMP/dump_${i}.txt" | tail -n +4 | sed 's/^/    /'
    dump_path="$REGRESSIONS_DIR/seed${SEED}_q${i}_${kind}.txt"
    {
      echo "# Reproduce: ./bench/query_fuzz.sh --seed $SEED --count $COUNT --stop-on-fail"
      cat "$TMP/dump_${i}.txt"
    } > "$dump_path"
    echo "  dumped to $dump_path"
    failure_paths+=("$dump_path")
    failed=$((failed + 1))
  done < "$MISMATCH_REPORT"
fi

echo ""
if [[ -s "$BATCH_ERR" ]]; then
  echo "DuckDB reported $(wc -l < "$BATCH_ERR" | tr -d ' ') stderr line(s) somewhere in the batch"
  echo "(a query the generator produced that DuckDB itself rejected — not"
  echo "necessarily a csvql bug; if a MISMATCH above looks like this, check"
  echo "whether the DuckDB output is simply missing for that query):"
  sed 's/^/  /' "$BATCH_ERR"
fi
# Two coverage numbers, measuring genuinely different things. Both dedup on
# csvql_sql (column 2): it's a 1:1 stand-in for duck_sql (same predicate,
# different table name only).
#
# `distinct` — unique query TEXT. Includes the randomly-drawn literals, so
# it mostly measures literal churn, not coverage: `WHERE salary != 90483`
# and `WHERE salary != 4122` are two distinct queries testing one code
# path. It does NOT saturate (measured: 81.5% distinct at count=50000,
# still 66.3% at 400000, climbing near-linearly throughout) because the
# numeric literals are drawn from wide ranges. Kept because it's the
# denominator-free "how much repetition was in this run" number, but it is
# NOT the saturation signal — it reads ~81% at count=50000 regardless of
# how wide the generator's templates are.
#
# `templates` — unique query SHAPE: literals normalized away and column
# names collapsed to their type class, leaving just the SQL surface being
# exercised. This is the number that actually plateaus, so it's the one
# that answers "has this seed/count stopped finding new query shapes, and
# does the generator need widening?". Measured: ~8,900 templates total,
# stable across seeds (8424/8434/8466 at count=200000 for seeds
# 99/12345/7); count=50000 reaches ~6,300 of them (~71%; 6311 and 6214 on
# two real seeds), count=200000 reaches ~8,400 (~95%), and +200000 more
# queries past that buys only ~450 new templates. A templates number that stops growing while the SQL
# surface csvql supports keeps growing is the signal to widen the
# templates — see VERIFICATION-LOG.md.
distinct="$(awk -F'\t' '{print $2}' "$QUERIES_FILE" | sort -u | wc -l | tr -d ' ')"

# The column names below are the fixture's schema (bench/gen_fixture.sh):
# change that schema and this list has to change with it, or shapes stop
# collapsing and the templates number silently inflates.
templates="$(awk -F'\t' -v q="'" '
function xform(t) {
  if (t == "id" || t == "age" || t == "salary") return "NUM"
  if (t == "name" || t == "city" || t == "department") return "STR"
  if (t ~ /^[0-9]+$/) return "N"
  return t
}
{
  s = $2
  # 1. Collapse quoted literals — the CSV path and every sampled string
  #    value — before tokenizing, so their contents (arbitrary text from
  #    the fixture) can never be mistaken for identifiers.
  out = ""
  while (match(s, q "[^" q "]*" q)) {
    lit = substr(s, RSTART, RLENGTH)
    out = out substr(s, 1, RSTART - 1) (index(lit, ".csv") ? "CSV" : "LIT")
    s = substr(s, RSTART + RLENGTH)
  }
  s = out s
  # 2. Token-level normalization, walking characters rather than using a
  #    word-boundary regex: those are not portable (GNU sed/awk spell them
  #    \b or \y, BSD spells them [[:<:]]/[[:>:]], and neither accepts the
  #    other), and this script runs on both ubuntu-latest and macos-14 in
  #    CI. A \b here would silently stop matching on macOS and report a
  #    different templates count for the same seed.
  res = ""; tok = ""
  n = length(s)
  for (i = 1; i <= n; i++) {
    c = substr(s, i, 1)
    if (c ~ /[A-Za-z0-9_]/) { tok = tok c } else { res = res xform(tok) c; tok = "" }
  }
  print res xform(tok)
}' "$QUERIES_FILE" | sort -u | wc -l | tr -d ' ')"

CSVQL_VERSION="$("$CSVQL" --version 2>&1 | awk '{print $2}')"
DUCKDB_VERSION="$("$DUCKDB" --version 2>&1 | awk '{print $1}' | tr -d 'v')"

echo "$total queries run ($distinct distinct text, $templates distinct templates), $failed mismatches, seed=$SEED"
echo "SUMMARY total=$total distinct=$distinct templates=$templates mismatches=$failed seed=$SEED csvql=$CSVQL_VERSION duckdb=$DUCKDB_VERSION"
echo "Reproduce (after ./bench/gen_fixture.sh, csvql $CSVQL_VERSION, duckdb $DUCKDB_VERSION):"
echo "  ./bench/query_fuzz.sh --seed $SEED --count $COUNT"
if [[ $failed -gt 0 ]]; then
  echo "Regression files:"
  for p in "${failure_paths[@]}"; do echo "  $p"; done
  printf "\n  ${RED}FAIL${RESET}\n"
  exit 1
fi
printf "  ${GREEN}%s generated queries, zero divergence from DuckDB.${RESET}\n" "$total"
